server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: "0884999440"
    url: jdbc:postgresql://localhost:5432/registration
    username: nikol
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect 
          format-sql: true
    show-sql: true

